export const GET_COURSES = 'GET_COURSES';
export const ADD_COURSE = 'ADD_COURSE';
export const COURSES_LOADING = 'COURSES_LOADING';
export const GET_COURSES_FROM_SCHEDULE = 'GET_COURSES_FROM_SCHEDULE';
export const ADD_COURSE_TO_SCHEDULE = 'ADD_COURSE_TO_SCHEDULE';
export const SCHEDULE_COURSES_LOADING = 'SCHEDULE_COURSES_LOADING';